services:
  database:
    container_name: jabas_flow_db
    image: mysql
    environment:                  
      MYSQL_ROOT_PASSWORD: "root"  
      MYSQL_DATABASE: jabas_flow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
